ARG tag=jammy
FROM ubuntu:${tag}
ENV DEBIAN_FRONTEND=noninteractive

# see https://asc.llnl.gov/sites/asc/files/2020-09/AMG_Summary_v1_7.pdf
RUN apt-get update && \
    apt-get install -y fftw3-dev fftw3 pdsh libfabric-dev libfabric1 \
        openssh-client openssh-server \
        dnsutils telnet strace cmake git g++ \
        mpich unzip bzip2

WORKDIR /opt
RUN git clone  https://github.com/LLNL/AMG.git && \
    cd ./AMG && \
    make

ENV PATH=/opt/AMG/test:$PATH
WORKDIR /opt/AMG
